### ISSUE TITLE
Feature 1: User can start a new game

### ISSUE THREAD

**Issue by samanthavivonia** [samanthavivonia/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can start a new game from the home page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User clicks "New Game" on the home page to begin configuring a new game to start playing.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/46618757/158305101-ff2238b3-740c-427e-9894-d53790733291.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/46618757/158305136-d098cf90-664f-4f42-aa29-0dfb069211c2.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create animated logo component
- [x] Create button component
- [x] Create link-button component
- [x] Create home page component

### 🧑‍⚕️ Clean Up

- [x] Ensure logo resizes on different screen sizes
